Repository wanted-running-sheep/cloud-worker, pull requests merged in 2022-07, with the labels that each got.

#6 ✨ feat: server 디렉토리 추가 및 api모듈 구현
  database/db.json
  package.json
  server/database/db.json
  server/index.js
  src/@types/api.d.ts
  src/api/http/httpRequest.ts
  src/api/instance/index.ts
  src/api/models/useRegion.ts
  src/pages/ApplyPage.tsx
Labels: ⚙️ 설정

#7 💄 style: 모바일 앱 레이아웃 추가
  src/components/MobileLayout.tsx
  src/routes/index.tsx
  src/styles/globalStyles.ts
  src/styles/theme.ts
Labels: 📱 UI

#9 ✨ feat: Title 컴포넌트 추가
  src/assets/icons/Close.tsx
  src/assets/icons/LeftDirection.tsx
  src/assets/icons/index.ts
  src/components/Title.tsx
Labels: 🕹️ 기능

#10 ♻️ refactor: api호출시 url파라미터 문자열 값 대신 객체로 접근 할 수 있도록 수정
  src/@types/enum.ts
  src/api/http/httpRequest.ts
  src/api/models/useRegion.ts
  src/pages/ApplyPage.tsx
Labels: ⬆️ 리팩토링

#11 ✨ feat: Input 컴포넌트 개발
  src/@types/enum.ts
  src/components/Input.tsx
  src/constants/validation.ts
  src/styles/theme.ts
  src/utils/formatString.ts
Labels: 🕹️ 기능

#14 ✨ feat: Label 컴포넌트 개발
  src/components/Label.tsx
  src/components/MobileLayout.tsx
Labels: 🕹️ 기능

#21 ✨ feat: 체크박스 컴포넌트 개발
  src/components/Checkbox.tsx
Labels: 🕹️ 기능

#19 ✨ feat: Transportation, RoundButton 컴포넌트 개발
  src/@types/enum.ts
  src/components/RoundButton.tsx
  src/components/TransportationList.tsx
Labels: 🕹️ 기능

#20 ✨ feat: Content 컴포넌트 개발 및 Title 리팩토링
  src/@types/enum.ts
  src/assets/icons/Close.tsx
  src/assets/icons/LeftDirection.tsx
  src/components/Content.tsx
  src/components/Title.tsx
  src/styles/theme.ts
Labels: 🕹️ 기능, ⬆️ 리팩토링

#18 ✨ feat: 모달 컴포넌트 개발
  src/@types/react.ts
  src/api/models/useRegion.ts
  src/components/Loading.tsx
  src/components/MobileLayout.tsx
  src/components/RegionModal/RegionContentBox.tsx
  src/components/RegionModal/TouchScroll.tsx
  src/components/RegionModal/index.tsx
  src/constants/index.ts
  src/pages/ApplyPage.tsx
  src/styles/mixins.ts
  src/styles/theme.ts
Labels: 📱 UI, 🕹️ 기능

#26 💄 style: Admin페이지 레이아웃 개발
  src/components/AdminLayout.tsx
  src/components/SectionHeader.tsx
  src/pages/AdminPage.tsx
  src/routes/index.tsx
Labels: 📱 UI

#29 ✨ feat: 유저 목록 데이터 페칭
  server/database/db.json
  server/database/region.json
  server/writeDB.js
  src/@types/api.d.ts
  src/@types/enum.ts
  src/api/models/useApplyUserModel.ts
  src/api/models/useRegionModel.ts
  src/pages/AdminPage.tsx
Labels: 🕹️ 기능

#23 ✨ feat: Radio 컴포넌트
  src/assets/icons/Checked.tsx
  src/assets/icons/index.ts
  src/components/Radio.tsx
  src/styles/globalStyles.ts
Labels: 🕹️ 기능

#32 ✨ feat: 엑셀 다운로드 개발
  src/components/SectionHeader.tsx
  src/pages/AdminPage.tsx
  src/utils/excelDownload.ts
Labels: 🕹️ 기능

#39 💄 style: 지원하기 페이지 컴포넌트 배치
  src/components/Input.tsx
  src/components/MobileLayout.tsx
  src/components/Radio.tsx
  src/components/TransportationList.tsx
  src/components/index.ts
  src/pages/ApplyPage.tsx
Labels: 📱 UI

#35 ✨ feat: 페이지네이션 개발
  server/database/db.json
  server/writeDB.js
  src/@types/enum.ts
  src/assets/icons/RightDirection.tsx
  src/assets/icons/index.ts
  src/components/RegionModal/TouchScroll.tsx
  src/components/UserList/Pangination.tsx
  src/components/UserList/Table.tsx
  src/components/UserList/UserList.tsx
  src/hooks/usePagination.ts
  src/pages/AdminPage.tsx
Labels: 🕹️ 기능

#42 💄 style: Login 페이지 추가
  src/components/Login.tsx
  src/components/index.ts
  src/constants/error.ts
  src/pages/AdminLoginPage.tsx
  src/pages/index.tsx
  src/routes/index.tsx
  src/styles/theme.ts
Labels: 📱 UI

#41 ♻️ refactor: 이용약관 라우터 추가
  src/components/Checkbox.tsx
  src/components/MobileLayout.tsx
  src/components/Title.tsx
  src/components/index.ts
  src/pages/AgreementPage.tsx
  src/pages/ApplyPage.tsx
  src/pages/index.tsx
  src/routes/index.tsx
Labels: 📱 UI, ⬆️ 리팩토링

#40 ♻️ refactor: admin 리팩토링
  src/@types/api.d.ts
  src/components/AdminLayout.tsx
  src/components/UserList/Pagination.tsx
  src/components/UserList/Tab.tsx
  src/components/UserList/Table.tsx
  src/components/UserList/Tooltip.tsx
  src/components/UserList/UserList.tsx
  src/components/index.ts
  src/hooks/useSearchUser.ts
  src/pages/AdminPage.tsx
  src/styles/globalStyles.ts
  src/styles/theme.ts
Labels: 📱 UI, ⬆️ 리팩토링

#44 🐛 fix: `지원하기` 할 때 데이터 순서 기존대로 잘 잡도록
  server/database/db.json
  src/@types/api.d.ts
  src/components/RegionModal/RegionContentBox.tsx
  src/pages/ApplyPage.tsx
  src/recoil/atoms.ts
Labels: 🐞 버그

#45 💄 style: 폰트 변경
  src/assets/css/font.css
  src/components/Login.tsx
  src/pages/AdminLoginPage.tsx
  src/pages/ApplyPage.tsx
  src/pages/LandingPage.tsx
  src/styles/globalStyles.ts
Labels: 📱 UI

#46 🐛 fix: 체크박스 버그 수정
  src/components/Checkbox.tsx
Labels: 🐞 버그
